Homework 29
SSSergiy/jsurok pull request #30
Opened 2022-11-17 01:55 UTC by SSSergiy

2022-11-17 12:50 UTC, vb-oiko requested changes
Дуже добре, але потрібно трохи вдосконалити валідацію:
- неможливо ввести імʼя кирилицею
- переплутані значення поля `afterPayment` для варіантів радіо перемикача
- можливо ввести відʼємне значення номеру складу Нової пошти
- можливо ввести відʼємну кількість товару

2022-11-18 08:20 UTC, vb-oiko commented on homeworks/index.html
> +								title="Разрешено от 3 до 20 символов" pattern="[A-Za-zа-яА-Я]{3,20}" >
А як же пробіли та апострофи? Ви впевнені що це спрацює?

2022-11-18 08:22 UTC, vb-oiko commented on homeworks/index.html
> +							<input class="form__input"   id="mailWarehouse" name="mailWarehouse" type="number" min="1"  pattern="[0-9]{3,20}">
навіщо тут паттерн? навіщо мінімальна кількість символів3 а максимальна 20?
схоже на копіпасту
на мій погляд можна задати максимальне значення, наприклад 1000

2022-11-18 08:22 UTC, vb-oiko commented on homeworks/index.html
> +							<input class="form__input"   id="numberOfGoods" name="numberOfGoods" type="number" min="1" pattern="[0-9]{3,20}">
знов копіпаста?

2022-11-18 16:01 UTC, SSSergiy commented on homeworks/index.html
> +							<input class="form__input"   id="numberOfGoods" name="numberOfGoods" type="number" min="1" pattern="[0-9]{3,20}">
роблю домашки вноч1, спочатку убираю патерни,а к к1нц1 знову ставлю,Забуваючи що ще не розум1ю регулярки.Дякую вам за вашу працю.

2022-12-02 15:51 UTC, merged